name: Deploy FTP and Update

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Web Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Synchronization SFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" "sftp://$FTP_SERVER" <<'EOF'
          set sftp:auto-confirm yes
          mirror --reverse --delete --verbose --exclude-glob .git* ./ "$FTP_SERVER_DIR"
          bye
          EOF
      - name: Run Update Script
        run: |
          curl -s "https://api.rollerlesloups.fr/update.php?secret=${{ secrets.DEPLOY_SECRET }}"
